### ISSUE TITLE
Usage with binary data ?

### ISSUE THREAD

**Issue by joeblew99** [kniren/gota#1]
This is useful for me. In the roadmap, have you considered  binary data ( images etc ) and tensors ?
I do a fair bit of ETL and fbp style work in golang, and so might be able to contribute

**Comment by kniren** [comment]
Hello, right now I'm working on storing arbitrary types inside the columns (A column can only have elements of the same type). This would allow to store lists or other data structures as cells inside the DataFrame matrix as long as they comply with the necessary interfaces.

How exactly do you want to use images or binary data with gota?

If it is for matrix computations I recommend you to take a look to https://github.com/gonum, for it is was conceived with that in mind.

Right now I'm focusing on data wrangling with this package, including things like subsetting, sorting, merging or function application but I don't discard adding more complex operations in the future.

**Comment by joeblew99** [comment]
The reason I asked is because I need to stream binary data through
different computation nodes.
Use cases are real time video transformations, real time convolution &
analysis.

Gonum and its packages I presume can do the computation, but dataframes and
other buffered data structures are still needed to move the data between
the compute nodes.

Curious what you think.

**Comment by kniren** [comment]
I suppose that you could implement your own type to store in the DataFrame cells, but keeping in mind your use cases I would say it makes more sense to use a less convoluted data structure: slice arrays, multidimensional arrays or hash maps should be able to do the job as long as you implement the real time algorithms correctly.

**Comment by joeblew99** [comment]
Your right.. Will try out different way
