### ISSUE TITLE
Which license applies to this repo

### ISSUE THREAD

**Issue by ifraixedes** [kniren/gota#2]
It looks a quite interesting project and you may find some people to collaborate, but without specifying a LICENSE is pretty hard that people decide to push something.

LICENSE can be any, some people may not like to collaborate depending on it, but at least specifying one, everybody will be clear, than having to fallback to whatever law.

Thanks for considering

**Comment by kniren** [comment]
You are absolutely right, starting on today's release v0.3.0 you can find that this package is licensed under the Apache v2 License.

Thank you four your feedback!

**Comment by ifraixedes** [comment]
Thanks!
