### ISSUE TITLE
how to handle the datetime type data?

### ISSUE THREAD

**Issue by guduxingzou** [kniren/gota#20]
does this supports datetime type data?
how to handle the datetime type data?

thanks!

**Comment by kniren** [comment]
Currently only 4 types are supported: `Int`, `Float`, `String` and `Bool`. In the future additional data types might be implemented and actually a `DateTime` type could be interesting.

As a workaround you can transform your dates to `int` as a measure of nanoseconds to be able to insert it as a `Int` column.

**Comment by guduxingzou** [comment]
ok  I will try  your method。 ths!
