### ISSUE TITLE
Nice initiative, It would be great if installation instructions for this package are added.

### ISSUE THREAD

**Issue by anandgavai** [kniren/gota#28]

**Comment by kniren** [comment]
You would install it as you would with any Go: `go get github.com/kniren/gota`

**Comment by kyp0717** [comment]
Something has changed.  go get does not work anymore ...
[m57311@cilsdbxd32293 go]$ go get github.com/kniren/gota
can't load package: package github.com/kniren/gota: no Go files in /home/SILVER/m57311/go/src/github.com/kniren/gota


[m57311@cilsdbxd32293 go]$ go version
go version go1.11.2 linux/amd64
