### ISSUE TITLE
Delete/Drop Function

### ISSUE THREAD

**Issue by benjmarshall** [kniren/gota#34]
Have you considered the addition of a delete/remove/drop type function? I've started to use your library and have come across a use case where it would be advantageous to be able to explicitly identify a column to be removed. Currently I would have to get all of the column names, find which index I want to remove, and then generate a series of indexes excluding that one to perform a Select operation.

I am happy to have a first pass at adding this type of function if there is a consensus it would be helpful.

**Comment by kniren** [comment]
Hello!

This was easy enough to implement and I think is a nice utility function to have.

You can find the implementation on the dev branch, please test it to see if it suits your use cases and let me know.

I called the method Deselect, although probably Drop is a better name. If all is good, you can send a PR with the name change and I will merge it, I'm a bit starved for time lately.

Best,
Alex

**Comment by benjmarshall** [comment]
Thanks, that seems to do the trick! I'll update the function name at submit a PR shortly.

**Comment by benjmarshall** [comment]
Have submitted PR #35 to change the function to Drop.

**Comment by kniren** [comment]
PR merged, thank you!
