### ISSUE TITLE
is this project dumped out

### ISSUE THREAD

**Issue by vikram-rawat** [kniren/gota#37]
are there any similar package or fork of this package to help us work well with dataframes.

Please at least reply if you are planning to drop the package.

**Comment by kniren** [comment]
Hi! The project has not been dropped although the development has slowed down.

Numerous contributions have been merged on `dev` and soon I will compile the next release of them.

If you need further functionality that is not on the issues you are welcome to open a new issue or contributing submitting PR!

Best,
Alex
