### ISSUE TITLE
Question about Type Accessor/conversion method

### ISSUE THREAD

**Issue by szaydel** [kniren/gota#46]
So while this is intentional, I wanted to make sure I understand reasoning before deciding how to work with this. Whereas Float() for example does not have two return parameters, Int() and Bool() do. What was the thinking there? Is the idea that some of these conversions more fellable than others?
```
// Accessor/conversion methods
Copy() Element     // FIXME: Returning interface is a recipe for pain
Val() ElementValue // FIXME: Returning interface is a recipe for pain
String() string
Int() (int, error)
Float() float64
Bool() (bool, error)

```

Thanks a lot, sorry if I am being dense...

**Comment by kniren** [comment]
Ints and bools don't have any way of representing values such as NA/NaN but floats do support it, hence the error returns for those cases.

I'm closing this issue, but feel free to comment here if you have further questions regarding this.

**Comment by szaydel** [comment]
Yep, good. That's what I assumed was the reason, but they assumptions are bad for business. :)

Thanks a lot!
